---

slurm_accounting_db_password: "{{ lookup('password', '/tmp/slurmpasswordfile chars=ascii_letters,digits,hexdigits') }}"

slurm_packages:
  - slurmctld
  - slurmdbd
  - libpmi

slurm_role: mgmt

slurm_elastic:
  oracle:
    config_directory: /home/slurm/.oci/

install_packages:
  - xorg-x11-xauth
  - openmpi-devel
  - python3-devel
  - "@Development Tools"
  - vim

mpi_packages:
  oracle:
    - openmpi3-devel
    - mpich-3.2-devel
  google:
    - openmpi3-devel
    - mpich-3.2-devel
  aws: []

monitoring_role: master
grafana_admin_password: "{{ lookup('password', '/tmp/grafanapasswordfile chars=ascii_letters,digits,hexdigits') }}"

bootstrap_ansible_pull_playbook: compute.yml

admin_key_path:
  oracle: /home/opc/.ssh/authorized_keys
  google: /home/provisioner/.ssh/authorized_keys
  aws: /home/centos/.ssh/authorized_keys
