---

- name: create directory for the finalised files
  file:
    path: /mnt/shared/finalised
    state: directory
    mode: 0755

- name: create the finalised file
  file:
    path: /mnt/shared/finalised/{{ ansible_hostname }}
    state: touch
    mode: 0777
