---
- name: restart firewalld
  service:
    name: firewalld
    state: restarted

- name: restart slurmdbd
  service:
    name: slurmdbd
    state: restarted

- name: restart slurmd
  service:
    name: slurmd
    state: restarted
  when: slurm_role == "compute"
